[package]
name = "whisper-stream-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
whisper-rs = { version = "0.14.2", features = ["metal", "coreml"] }
cpal = "0.15"
reqwest = { version = "0.12", features = ["blocking"] }
dirs = "5.0"
hound = "3"
ctrlc = "3"
rubato = "0.15"
