[package]
name = "whisper-stream-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
whisper-rs = { version = "0.14.2", features = ["metal", "coreml"] }
cpal = "0.15.3"
reqwest = { version = "0.12", features = ["blocking"] }
dirs = "5.0.1"
hound = "3.5.1"
ctrlc = "3"
rubato = "0.15"
anyhow = "1.0.75"
indicatif = "0.17.7"
thiserror = "1.0"

[[example]]
name = "commandline"
path = "examples/commandline.rs"